import type { LegalBlock, LegalSection } from "../_components/legal-page";

// Hand-converted from Brad's "privacy policy.odt" (docs/legal/, 26 August 2026).
// The only deviation from the document is that the author's drafting note in
// the preamble is omitted.

export const PREAMBLE: LegalBlock[] = [
  { type: "address", lines: [
    "Book My Tech Ltd",
    "Company number: 17379663",
    "Registered office: 2 Syerscote Lane, Wigginton, B79 9DX, United Kingdom",
    "Email: support@bookmytech.co.uk",
  ] },
];

export const SECTIONS: LegalSection[] = [
  {
    heading: "About this Privacy Policy",
    blocks: [
      { type: "p", text: "Book My Tech Ltd (“Book My Tech”, “we”, “us” or “our”) operates an online platform that connects customers with vetted independent mechanics." },
      { type: "p", text: "This Privacy Policy explains how we collect, use, store and share personal information when you:" },
      {
        type: "bullets",
        items: [
          "visit our website;",
          "create an account;",
          "request or make a booking;",
          "receive services through Book My Tech;",
          "communicate with a mechanic;",
          "communicate with our support team;",
          "make or receive payments;",
          "register as a mechanic; or",
          "otherwise use our services.",
        ],
      },
      { type: "p", text: "We take privacy seriously and handle personal information in accordance with applicable UK data protection legislation, including the UK GDPR, Data Protection Act 2018 and, where applicable, Privacy and Electronic Communications Regulations (PECR)." },
    ],
  },
  {
    heading: "Who is Book My Tech?",
    blocks: [
      { type: "p", text: "Book My Tech Ltd is the company responsible for operating the Book My Tech platform." },
      { type: "address", lines: [
        "Book My Tech Ltd",
        "Company number: 17379663",
        "2 Syerscote Lane",
        "Wigginton",
        "B79 9DX",
        "United Kingdom",
        "Email: support@bookmytech.co.uk",
      ] },
      { type: "p", text: "For most information collected through our platform, Book My Tech is the data controller." },
    ],
  },
  {
    heading: "What information do we collect?",
    blocks: [
      { type: "p", text: "The information we collect depends on how you use Book My Tech." },
      { type: "p", text: "If you are a customer, we may collect:" },
      {
        type: "bullets",
        items: [
          "your name;",
          "email address;",
          "telephone number;",
          "address;",
          "vehicle location;",
          "vehicle registration number;",
          "vehicle make and model;",
          "vehicle mileage;",
          "vehicle details;",
          "information about your vehicle’s condition;",
          "requested repairs or services;",
          "photographs;",
          "booking information;",
          "quotations;",
          "payment and transaction information;",
          "communications with us and mechanics;",
          "reviews and ratings;",
          "warranty information; and",
          "information relating to complaints or disputes.",
        ],
      },
      { type: "p", text: "If you are a mechanic, we may collect:" },
      {
        type: "bullets",
        items: [
          "your name;",
          "business or trading name;",
          "address;",
          "telephone number;",
          "email address;",
          "date of birth where required;",
          "identity information;",
          "proof of address;",
          "qualifications;",
          "experience;",
          "insurance details;",
          "business details;",
          "right-to-work information where applicable;",
          "bank/payment information;",
          "profile information;",
          "photographs;",
          "booking history;",
          "customer feedback;",
          "warranty information; and",
          "information required for our vetting process.",
        ],
      },
    ],
  },
  {
    heading: "Vehicle information",
    blocks: [
      { type: "p", text: "As an automotive marketplace, Book My Tech needs certain information about vehicles." },
      { type: "p", text: "This may include:" },
      {
        type: "bullets",
        items: [
          "registration number;",
          "make;",
          "model;",
          "year;",
          "mileage;",
          "engine information;",
          "service information;",
          "repair information;",
          "diagnostic information;",
          "reported faults;",
          "photographs;",
          "parts fitted; and",
          "warranty information.",
        ],
      },
      { type: "p", text: "Vehicle information may be considered personal information where it can be linked to an identifiable individual." },
    ],
  },
  {
    heading: "Information about your use of our website",
    blocks: [
      { type: "p", text: "When you visit our website, we may automatically receive certain technical information, such as:" },
      {
        type: "bullets",
        items: [
          "IP address;",
          "browser type;",
          "device type;",
          "operating system;",
          "pages visited;",
          "approximate location;",
          "referring website;",
          "website activity;",
          "timestamps;",
          "error information; and",
          "information collected through cookies and similar technologies.",
        ],
      },
      { type: "p", text: "Our use of cookies is explained in our separate Cookie Policy." },
    ],
  },
  {
    heading: "How do we collect your information?",
    blocks: [
      { type: "p", text: "We may collect information:" },
      {
        type: "bullets",
        items: [
          "directly from you;",
          "when you create an account;",
          "when you request a booking;",
          "when you make a booking;",
          "when you submit a quotation;",
          "when you register as a mechanic;",
          "during mechanic onboarding;",
          "during mechanic vetting;",
          "when you contact customer support;",
          "when you communicate through the platform;",
          "when you make a payment;",
          "when you submit a review;",
          "through cookies and similar technologies; and",
          "from third parties where legally permitted.",
        ],
      },
    ],
  },
  {
    heading: "Why do we use your information?",
    blocks: [
      { type: "p", text: "We use personal information to operate Book My Tech and provide our services." },
      { type: "p", text: "This may include:" },
      { type: "h3", text: "Providing the service" },
      { type: "p", text: "We use information to:" },
      {
        type: "bullets",
        items: [
          "arrange bookings;",
          "connect customers with mechanics;",
          "provide booking details;",
          "manage quotations;",
          "facilitate repairs;",
          "communicate about bookings;",
          "process payments;",
          "administer warranties; and",
          "provide customer support.",
        ],
      },
      { type: "h3", text: "Keeping the platform safe" },
      { type: "p", text: "We may use information to:" },
      {
        type: "bullets",
        items: [
          "vet mechanics;",
          "verify information;",
          "prevent fraud;",
          "investigate suspicious activity;",
          "protect customers;",
          "protect mechanics;",
          "protect Book My Tech;",
          "maintain platform security; and",
          "enforce our Terms & Conditions.",
        ],
      },
      { type: "h3", text: "Improving Book My Tech" },
      { type: "p", text: "We may analyse information to:" },
      {
        type: "bullets",
        items: [
          "improve our website;",
          "improve the booking process;",
          "understand how our platform is used;",
          "identify technical problems;",
          "improve customer service; and",
          "develop new services.",
        ],
      },
      { type: "h3", text: "Legal and regulatory purposes" },
      { type: "p", text: "We may process information where necessary to:" },
      {
        type: "bullets",
        items: [
          "comply with legal obligations;",
          "respond to lawful requests;",
          "deal with disputes;",
          "establish or defend legal claims; and",
          "meet accounting and tax requirements.",
        ],
      },
    ],
  },
  {
    heading: "Our legal basis for using your information",
    blocks: [
      { type: "p", text: "The UK GDPR requires us to have a lawful basis for processing personal information." },
      { type: "p", text: "Depending on the circumstances, we may rely on:" },
      { type: "h3", text: "Contract" },
      { type: "p", text: "Where processing is necessary to provide the services you have requested." },
      { type: "p", text: "For example, processing a booking or arranging a mechanic." },
      { type: "h3", text: "Legal obligation" },
      { type: "p", text: "Where we need to process information to comply with the law." },
      { type: "h3", text: "Legitimate interests" },
      { type: "p", text: "Where processing is necessary for our legitimate interests, provided those interests are not overridden by your rights." },
      { type: "p", text: "This can include:" },
      {
        type: "bullets",
        items: [
          "platform security;",
          "fraud prevention;",
          "mechanic vetting;",
          "improving our services;",
          "enforcing our Terms;",
          "protecting customers and mechanics; and",
          "operating our business.",
        ],
      },
      { type: "h3", text: "Consent" },
      { type: "p", text: "Where we are required to obtain your consent, such as for certain marketing or non-essential cookies." },
      { type: "p", text: "You can withdraw consent where consent is our legal basis." },
    ],
  },
  {
    heading: "Sharing your information with mechanics",
    blocks: [
      { type: "p", text: "When you make a booking, we need to provide the mechanic with information necessary to complete the job." },
      { type: "p", text: "This may include:" },
      {
        type: "bullets",
        items: [
          "your name;",
          "contact details;",
          "booking address;",
          "vehicle information;",
          "requested work;",
          "booking details; and",
          "information reasonably required to complete the booking.",
        ],
      },
      { type: "p", text: "Mechanics are expected to keep customer information secure and use it only for legitimate purposes connected with the Book My Tech booking." },
    ],
  },
  {
    heading: "Protecting customers from off-platform activity",
    blocks: [
      { type: "p", text: "Book My Tech is a platform-based service." },
      { type: "p", text: "Information provided to mechanics through Book My Tech must not be used to circumvent the platform." },
      { type: "p", text: "Mechanics must not use customer information obtained through Book My Tech to:" },
      {
        type: "bullets",
        items: [
          "arrange private work;",
          "provide private quotations;",
          "arrange private payments;",
          "arrange future work outside Book My Tech; or",
          "otherwise bypass the platform.",
        ],
      },
      { type: "p", text: "This helps protect customers, mechanics and the integrity of our marketplace." },
    ],
  },
  {
    heading: "Additional work",
    blocks: [
      { type: "p", text: "If additional work is identified during a booking, the additional work must be dealt with through the Book My Tech platform." },
      { type: "p", text: "Mechanics must not use customer information obtained through Book My Tech to privately quote or arrange additional work." },
      { type: "p", text: "This allows the work to remain properly recorded and subject to the applicable Book My Tech terms, payment process and protections." },
    ],
  },
  {
    heading: "Sharing information with customers",
    blocks: [
      { type: "p", text: "Where appropriate, customers may be shown information about the mechanic carrying out their booking." },
      { type: "p", text: "This may include:" },
      {
        type: "bullets",
        items: [
          "mechanic name;",
          "business name;",
          "profile information;",
          "relevant qualifications or experience;",
          "ratings; and",
          "reviews.",
        ],
      },
      { type: "p", text: "We aim to provide enough information to allow customers to make informed decisions without unnecessarily exposing personal information." },
    ],
  },
  {
    heading: "Mechanic vetting",
    blocks: [
      { type: "p", text: "Book My Tech vets mechanics before they are accepted onto the platform." },
      { type: "p", text: "This may involve checking information such as:" },
      {
        type: "bullets",
        items: [
          "identity;",
          "qualifications;",
          "experience;",
          "insurance;",
          "business information;",
          "professional suitability; and",
          "other information relevant to our onboarding requirements.",
        ],
      },
      { type: "p", text: "Where appropriate, we may use third-party providers to help carry out checks." },
    ],
  },
  {
    heading: "Payments",
    blocks: [
      { type: "p", text: "Book My Tech uses Stripe to facilitate payments." },
      { type: "p", text: "Payment information may be processed to:" },
      {
        type: "bullets",
        items: [
          "complete transactions;",
          "verify payments;",
          "prevent fraud;",
          "process refunds;",
          "handle chargebacks; and",
          "comply with legal requirements.",
        ],
      },
      { type: "p", text: "Where payment-card information is handled directly by Stripe, Book My Tech does not intend to store complete payment-card details on its own systems." },
      { type: "p", text: "Stripe may process personal information under its own privacy terms." },
    ],
  },
  {
    heading: "Service providers",
    blocks: [
      { type: "p", text: "We may use trusted third parties to help operate Book My Tech." },
      { type: "p", text: "These may include providers of:" },
      {
        type: "bullets",
        items: [
          "hosting;",
          "cloud storage;",
          "email;",
          "communications;",
          "payment services;",
          "analytics;",
          "customer support;",
          "security;",
          "fraud prevention;",
          "identity verification; and",
          "technical services.",
        ],
      },
      { type: "p", text: "We take appropriate steps to ensure that personal information is protected when third parties process it on our behalf." },
    ],
  },
  {
    heading: "When we may disclose information",
    blocks: [
      { type: "p", text: "We may disclose personal information where reasonably necessary to:" },
      {
        type: "bullets",
        items: [
          "provide our services;",
          "process payments;",
          "arrange bookings;",
          "operate our platform;",
          "prevent fraud;",
          "investigate misuse;",
          "comply with the law;",
          "respond to lawful requests;",
          "enforce our Terms & Conditions;",
          "protect customers;",
          "protect mechanics;",
          "protect Book My Tech; or",
          "establish, exercise or defend legal claims.",
        ],
      },
    ],
  },
  {
    heading: "Marketing",
    blocks: [
      { type: "p", text: "Where permitted by law, we may contact you about:" },
      {
        type: "bullets",
        items: [
          "Book My Tech services;",
          "offers;",
          "promotions;",
          "new features;",
          "automotive services; and",
          "relevant updates.",
        ],
      },
      { type: "p", text: "You can opt out of marketing communications at any time." },
      { type: "p", text: "You will still receive essential service communications where necessary, such as:" },
      {
        type: "bullets",
        items: [
          "booking confirmations;",
          "booking updates;",
          "payment information;",
          "account notices;",
          "warranty information; and",
          "important service announcements.",
        ],
      },
    ],
  },
  {
    heading: "Cookies",
    blocks: [
      { type: "p", text: "Book My Tech uses cookies and similar technologies." },
      { type: "p", text: "These may be used for:" },
      {
        type: "bullets",
        items: [
          "essential website functionality;",
          "security;",
          "account functionality;",
          "remembering preferences;",
          "analytics; and",
          "marketing where permitted.",
        ],
      },
      { type: "p", text: "Please see our separate Cookie Policy for more information." },
    ],
  },
  {
    heading: "UK GDPR rights",
    blocks: [
      { type: "p", text: "Depending on the circumstances, you have rights under the UK GDPR, including:" },
      {
        type: "bullets",
        items: [
          "Right of access — request a copy of your personal information.",
          "Right to rectification — ask us to correct inaccurate information.",
          "Right to erasure — ask us to delete information in certain circumstances.",
          "Right to restriction — ask us to restrict processing in certain circumstances.",
          "Right to object — object to certain processing.",
          "Right to data portability — request certain information in a portable format.",
          "Right to withdraw consent — where processing is based on consent.",
          "Rights relating to automated decision-making — where applicable.",
        ],
      },
      { type: "p", text: "These rights are subject to legal conditions and exceptions." },
    ],
  },
  {
    heading: "Exercising your rights",
    blocks: [
      { type: "p", text: "To make a data-protection request, contact:" },
      { type: "p", text: "support@bookmytech.co.uk" },
      { type: "p", text: "We may need to verify your identity before completing your request." },
      { type: "p", text: "We will normally respond within one month of receiving a valid request, although this can be extended where permitted by the UK GDPR for complex or multiple requests." },
      { type: "p", text: "We will normally deal with GDPR requests free of charge." },
    ],
  },
  {
    heading: "Data retention",
    blocks: [
      { type: "p", text: "We do not keep personal information forever." },
      { type: "p", text: "We retain information for as long as reasonably necessary, taking into account:" },
      {
        type: "bullets",
        items: [
          "the purpose for which it was collected;",
          "contractual requirements;",
          "warranty obligations;",
          "tax and accounting requirements;",
          "legal obligations;",
          "disputes;",
          "fraud prevention;",
          "platform security; and",
          "legitimate business requirements.",
        ],
      },
      { type: "p", text: "When information is no longer required, we will take reasonable steps to securely delete or anonymise it." },
    ],
  },
  {
    heading: "International transfers",
    blocks: [
      { type: "p", text: "Some of our service providers may process information outside the UK." },
      { type: "p", text: "Where this happens, we will use appropriate safeguards required under UK data protection law for international transfers." },
    ],
  },
  {
    heading: "Security",
    blocks: [
      { type: "p", text: "We take reasonable technical and organisational measures to protect personal information against:" },
      {
        type: "bullets",
        items: [
          "unauthorised access;",
          "accidental loss;",
          "destruction;",
          "alteration;",
          "disclosure;",
          "misuse; and",
          "unlawful processing.",
        ],
      },
      { type: "p", text: "However, no online service can guarantee absolute security." },
    ],
  },
  {
    heading: "Data breaches",
    blocks: [
      { type: "p", text: "If we become aware of a personal data breach, we will assess and investigate it and take appropriate action." },
      { type: "p", text: "Where legally required, we may notify the ICO and affected individuals." },
    ],
  },
  {
    heading: "Reviews and ratings",
    blocks: [
      { type: "p", text: "If you submit a review or rating, some information may be displayed to other users or publicly on our platform." },
      { type: "p", text: "Please do not include unnecessary personal information in a review." },
      { type: "p", text: "We may remove or moderate reviews that breach our Terms & Conditions or applicable law." },
    ],
  },
  {
    heading: "Communications through Book My Tech",
    blocks: [
      { type: "p", text: "Communications between customers, mechanics and Book My Tech may be processed and retained where reasonably necessary for:" },
      {
        type: "bullets",
        items: [
          "booking administration;",
          "customer support;",
          "dispute resolution;",
          "warranty administration;",
          "fraud prevention;",
          "platform security;",
          "quality control; and",
          "enforcing our Terms & Conditions.",
        ],
      },
    ],
  },
  {
    heading: "Fraud and platform protection",
    blocks: [
      { type: "p", text: "We may monitor and process information where reasonably necessary to detect and prevent:" },
      {
        type: "bullets",
        items: [
          "fraud;",
          "payment abuse;",
          "fake bookings;",
          "account abuse;",
          "attempts to bypass Book My Tech;",
          "off-platform activity;",
          "misuse of customer information; and",
          "other activity that could harm customers, mechanics or Book My Tech.",
        ],
      },
      { type: "p", text: "Any such processing will be carried out in accordance with applicable data protection law." },
    ],
  },
  {
    heading: "Children’s information",
    blocks: [
      { type: "p", text: "Book My Tech’s services are intended primarily for adults." },
      { type: "p", text: "We do not knowingly collect children’s personal information where doing so would be unlawful." },
      { type: "p", text: "If you believe that a child has provided personal information to us, contact:" },
      { type: "p", text: "support@bookmytech.co.uk" },
    ],
  },
  {
    heading: "Automated decision-making",
    blocks: [
      { type: "p", text: "Book My Tech does not currently intend to make decisions producing legal or similarly significant effects solely through automated processing without appropriate safeguards." },
      { type: "p", text: "Where applicable, we will provide information about automated decision-making and your rights under the UK GDPR." },
    ],
  },
  {
    heading: "Complaints",
    blocks: [
      { type: "p", text: "If you have concerns about how we have handled your personal information, please contact us first." },
      { type: "address", lines: [
        "Book My Tech Ltd",
        "2 Syerscote Lane",
        "Wigginton",
        "B79 9DX",
        "United Kingdom",
        "Email: support@bookmytech.co.uk",
      ] },
      { type: "p", text: "We will investigate your complaint and aim to resolve it." },
    ],
  },
  {
    heading: "Information Commissioner’s Office",
    blocks: [
      { type: "p", text: "You have the right to complain to the UK’s data protection regulator, the Information Commissioner’s Office (ICO), at ico.org.uk." },
      { type: "p", text: "You can contact the ICO directly, although we encourage you to contact Book My Tech first so that we have an opportunity to resolve your concern." },
    ],
  },
  {
    heading: "Changes to this Privacy Policy",
    blocks: [
      { type: "p", text: "We may update this Privacy Policy from time to time to reflect:" },
      {
        type: "bullets",
        items: [
          "changes to our services;",
          "changes to our technology;",
          "changes to applicable law;",
          "changes to our suppliers; or",
          "changes to how we process personal information.",
        ],
      },
      { type: "p", text: "The latest version will always be published on our website." },
    ],
  },
  {
    heading: "Contact Book My Tech",
    blocks: [
      { type: "p", text: "If you have any questions about this Privacy Policy or how we use your personal information:" },
      { type: "address", lines: [
        "Book My Tech Ltd",
        "Company number: 17379663",
        "2 Syerscote Lane",
        "Wigginton",
        "B79 9DX",
        "United Kingdom",
        "Email: support@bookmytech.co.uk",
      ] },
    ],
  },
];
